services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    environment:
      - NODE_ENV=production
    command: npm start
    restart: unless-stopped
    mem_limit: 512m
    cpus: 1